"""added added_at field in file model

Revision ID: ad06fa77519b
Revises: 193f603a4050
Create Date: 2026-02-04 20:40:21.303006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad06fa77519b'
down_revision: Union[str, Sequence[str], None] = '193f603a4050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('added_at', postgresql.TIMESTAMP(), nullable=False))
    op.alter_column('file', 'owner',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'owner',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('file', 'added_at')
    # ### end Alembic commands ###
